# Generated by Django 2.1.2 on 2018-11-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_tag', models.CharField(blank=True, max_length=25, null=True)),
                ('narrow_tag', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('slug_field', models.SlugField(blank=True, max_length=15, null=True)),
                ('uniqueid', models.CharField(max_length=36, verbose_name='UID')),
                ('ownervalue', models.IntegerField()),
                ('creation', models.DateField()),
                ('notation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('iso', 'name')},
        ),
        migrations.AddField(
            model_name='cinema',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.Customer'),
        ),
    ]
